### ISSUE TITLE
Fetching a lot of the same files without cache.

### ISSUE THREAD

**Issue by tsutoringo** [BlueMap-Minecraft/BlueMapWeb#1]
Fetching a lot of the same files without cache.
![image](https://user-images.githubusercontent.com/33830878/112972491-450e9f80-918b-11eb-8f4c-398d54ddac7f.png)

Sorry if my English is incorrect.
Thanks.

**Comment by tsutoringo** [comment]
https://github.com/BlueMap-Minecraft/BlueMapWeb/blob/4e81bb4abde65464b1ea66562dcd97040099867f/src/map/Map.js#L205

**Comment by TBlueF** [comment]
I purposely didn't optimize that because it's a side-effect in preparation for future changes:

In the future there will most likely be a separate `settings.json` file for each map, and the web-app will need to load them individually. This process should not block the loading of the actual app (should be a background-process) and is only necessary to display the correct world-names in the map-menu.

**Comment by tsutoringo** [comment]
I see😀
Thanks for the reply!
